export type EMAILVALIDATION = 'VALID' | 'INVALID';
export type PASSWORDVALIDATIONERROR = 'SHORT' | 'MISS_SPECIAL' | 'MISS_NUM' | 'MISS_UPCASE' | 'MISS_LOWCASE';

export type PASSWORDVALIDATION = 'VALID' | PASSWORDVALIDATIONERROR;